[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
proc_macros = { path = "proc_macros" }
derive-new = "0.6.0"
strum = "0.26.2"
strum_macros = "0.26.2"
